language:
  python

matrix:
  include:
    # Do they have it?
    #- os: linux
    #  dist: bionic
    #  python: 3.9
    # https://travis-ci.community/t/how-to-skip-python-download-to-osx-image-and-avoid-download-unavailable-error/9554/2
    - name: "Python 3.7.5 on macOS 10.14"
      os: osx
      language: shell       # 'language: python' is an error on Travis CI macOS
      osx_image: xcode10.2  # Python 3.7.5 running on macOS 10.14.3
    - name: "Python 3.7.4  on macOS 10.14.4"
      os: osx
      language: shell       # 'language: python' is an error on Travis CI macOS
      osx_image: xcode11.2
    - name: "Python 3.8.0 on macOS 10.14"
      os: osx
      language: shell       # 'language: python' is an error on Travis CI macOS
      osx_image: xcode11.3
    - os: osx
      language: shell       # 'language: python' is an error on Travis CI macOS
      osx_image: xcode12.4

    - name: "Python 3.5.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4
        - refreshenv
        - python3 --version
        - python3 -m pip install --upgrade pip
        - python3 -m pip install --upgrade codecov pytest
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - refreshenv
        - python3 --version
        - python3 -m pip install --upgrade pip
        - python3 -m pip install --upgrade codecov pytest
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.9 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.9
        - refreshenv
        - python3 --version
        - python3 -m pip install --upgrade pip
        - python3 -m pip install --upgrade codecov pytest
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.8
        - refreshenv
        - python3 --version
        - python3 -m pip install --upgrade pip
        - python3 -m pip install --upgrade codecov pytest
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    - name: "Python 3.9.2 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.9.2
        - python3 --version
        - python3 -m pip install --upgrade pip
        - python3 -m pip install --upgrade codecov pytest
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH

    - os: linux
      dist: focal
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: focal
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: focal
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: focal
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: focal
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: focal
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: focal
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: focal
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: focal
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: focal
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: focal
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: focal
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: focal
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: focal
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: focal
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: focal
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: focal
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: focal
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: focal
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: focal
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: focal
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: focal
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: focal
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: focal
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: focal
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: focal
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: focal
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: focal
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: groovy
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: groovy
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: groovy
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: groovy
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: groovy
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: groovy
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: groovy
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: groovy
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: groovy
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: groovy
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: groovy
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: groovy
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: groovy
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: groovy
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: groovy
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: groovy
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: groovy
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: groovy
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: groovy
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: groovy
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: groovy
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: groovy
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: groovy
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: groovy
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: groovy
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: groovy
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: groovy
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: groovy
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: bionic
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: bionic
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: bionic
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: bionic
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: bionic
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: bionic
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: bionic
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: bionic
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: bionic
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: bionic
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: bionic
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: bionic
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: bionic
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: bionic
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: bionic
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: bionic
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: bionic
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: bionic
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: bionic
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: bionic
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: bionic
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: bionic
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: bionic
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: bionic
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: bionic
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: bionic
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: bionic
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: bionic
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: xenial
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: xenial
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: xenial
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: xenial
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: xenial
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: xenial
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: xenial
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: xenial
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: xenial
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: xenial
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: xenial
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: xenial
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: xenial
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: xenial
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: xenial
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: xenial
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: xenial
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: xenial
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: xenial
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: xenial
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: xenial
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: xenial
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: xenial
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: xenial
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: xenial
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: xenial
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: xenial
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: xenial
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: trusty
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: trusty
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: trusty
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: trusty
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: trusty
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: trusty
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: trusty
      python: 3.6
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: trusty
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: trusty
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: trusty
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: trusty
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: trusty
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: trusty
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: trusty
      python: 3.7
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: trusty
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: trusty
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: trusty
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: trusty
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: trusty
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: trusty
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: trusty
      python: 3.8
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

    - os: linux
      dist: trusty
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.8.1"
              

    - os: linux
      dist: trusty
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.8.0"
              

    - os: linux
      dist: trusty
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.7.1"
              

    - os: linux
      dist: trusty
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.7.0"
              

    - os: linux
      dist: trusty
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.6.0"
              

    - os: linux
      dist: trusty
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.5.1"
              

    - os: linux
      dist: trusty
      python: 3.9
      env: TORCH_PIP_PACKAGE="torch==1.5.0"
              

before_install:
  - python3 --version
  - pip3 install -U pip
  - pip3 install -U pytest codecov
  - pip3 install $TORCH_PIP_PACKAGE --progress-bar off
install:
  - pip3 install ".[test]" . # install package + test dependencies
script:
  - TORCHSYNTH_DEBUG=True pytest
  - python3 examples/examples.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
